import { EditableContent, EditableContentGroup, ManagedContentItem } from "@/types/content";

const initialUpdatedAt = "2026-05-25T00:00:00.000Z";

export const defaultEditableContent: EditableContent[] = [
  {
    id: "content-home-hero-title",
    key: "home.hero.title",
    title: "Hero basligi",
    content: "Dijital tehditleri sade risk sinyallerine donustur.",
    updatedAt: initialUpdatedAt,
    updatedBy: "system"
  },
  {
    id: "content-home-hero-description",
    key: "home.hero.description",
    title: "Hero aciklamasi",
    content: "Sahte site, phishing link, riskli satici, supheli SMS ve dijital risk sinyallerini herkesin anlayacagi guven raporlarina ceviren AI destekli analiz platformu.",
    updatedAt: initialUpdatedAt,
    updatedBy: "system"
  },
  {
    id: "content-home-about-text",
    key: "home.about.text",
    title: "Hakkimizda metni",
    content: "Dijital Iz Avcisi, cevrim ici alisverislerde kullanicilarin urun ve satici risk sinyallerini daha hizli gorebilmesi icin gelistirilen AI destekli analiz platformudur.",
    updatedAt: initialUpdatedAt,
    updatedBy: "system"
  },
  {
    id: "content-home-cyber-news-title",
    key: "home.cyberNews.title",
    title: "Siber Gündem basligi",
    content: "Guncel dijital risk notlari.",
    updatedAt: initialUpdatedAt,
    updatedBy: "system"
  },
  {
    id: "content-home-cyber-news-description",
    key: "home.cyberNews.description",
    title: "Siber Gündem aciklamasi",
    content: "Turkiye odakli kisa, net ve aksiyon alinabilir guvenlik bultenleri.",
    updatedAt: initialUpdatedAt,
    updatedBy: "system"
  },
  {
    id: "content-home-security-center-description",
    key: "home.securityCenter.description",
    title: "Dijital Guvenlik Merkezi aciklamasi",
    content: "Kisa, net ve uygulanabilir risk uyarilariyla dijital tehditleri daha okunabilir hale getirir.",
    updatedAt: initialUpdatedAt,
    updatedBy: "system"
  },
  {
    id: "content-home-footer-description",
    key: "home.footer.description",
    title: "Footer aciklamasi",
    content: "AI destekli analizler bilgilendirme amaclidir. Platform kesin suclama yapmaz; riskli davranis, phishing paterni ve supheli sinyal dilini kullanir.",
    updatedAt: initialUpdatedAt,
    updatedBy: "system"
  },
  {
    id: "content-contact-intro-text",
    key: "contact.intro.text",
    title: "Iletisim alani metni",
    content: "Supheli link, sahte SMS ornegi, hatali analiz bildirimi veya yeni ozellik onerilerini bu form uzerinden paylasabilirsiniz.",
    updatedAt: initialUpdatedAt,
    updatedBy: "system"
  },
  {
    id: "content-home-announcement-banner",
    key: "home.announcement.banner",
    title: "Ana sayfa duyuru banneri",
    content: "Demo bulten: Sahte kargo SMS'leri ve marka taklidi yapan linkler icin analiz panelini kullanarak risk sinyallerini kontrol edin.",
    updatedAt: initialUpdatedAt,
    updatedBy: "system"
  },
  {
    id: "content-home-today-cyber-event-text",
    key: "home.todayCyberEvent.text",
    title: "Bugunun Siber Olayi metni",
    content: "Bu olay, dijital guvenlikte tek bir teknik acigin genis olcekli toplumsal ve kurumsal etkilere yol acabilecegini gosterir.",
    updatedAt: initialUpdatedAt,
    updatedBy: "system"
  }
];

export const editableContentGroups: EditableContentGroup[] = [
  {
    id: "homepage",
    title: "Ana sayfa",
    description: "Hero, duyuru, siber gundem ve guvenlik merkezi metinleri.",
    keys: [
      "home.hero.title",
      "home.hero.description",
      "home.announcement.banner",
      "home.securityCenter.description",
      "home.cyberNews.title",
      "home.cyberNews.description",
      "home.todayCyberEvent.text",
      "home.footer.description"
    ]
  },
  {
    id: "corporate",
    title: "Kurumsal sayfalar",
    description: "Hakkimizda ve iletisim alanlarinda kullanilan metinler.",
    keys: ["home.about.text", "contact.intro.text"]
  }
];

export const defaultManagedContent: ManagedContentItem[] = [
  {
    id: "mc-home-hero",
    type: "hero",
    title: "Dijital tehditleri sade risk sinyallerine donustur.",
    subtitle: "Vatandaslar icin AI destekli dijital guvenlik",
    description:
      "Sahte site, phishing link, riskli satici, supheli SMS ve dijital risk sinyallerini herkesin anlayacagi guven raporlarina ceviren AI destekli analiz platformu.",
    body: "",
    category: "Ana sayfa",
    tags: ["hero", "ai", "guvenlik"],
    imageUrl: "",
    altText: "Dijital Iz Avcisi risk radari",
    icon: "DI",
    ctaLabel: "Sorgu Panelini Ac",
    ctaHref: "/sorgu-paneli",
    status: "published",
    order: 1,
    isFeatured: true,
    createdAt: initialUpdatedAt,
    updatedAt: initialUpdatedAt
  },
  {
    id: "mc-nav-about",
    type: "navbar",
    title: "Hakkimizda",
    subtitle: "",
    description: "",
    body: "",
    category: "Navbar",
    tags: ["nav"],
    imageUrl: "",
    altText: "",
    icon: "",
    ctaLabel: "Hakkimizda",
    ctaHref: "/hakkimizda",
    status: "published",
    order: 1,
    isFeatured: false,
    createdAt: initialUpdatedAt,
    updatedAt: initialUpdatedAt
  },
  {
    id: "mc-nav-archive",
    type: "navbar",
    title: "Siber Arsiv",
    subtitle: "",
    description: "",
    body: "",
    category: "Navbar",
    tags: ["nav"],
    imageUrl: "",
    altText: "",
    icon: "",
    ctaLabel: "Siber Arsiv",
    ctaHref: "/siber-arsiv",
    status: "published",
    order: 2,
    isFeatured: false,
    createdAt: initialUpdatedAt,
    updatedAt: initialUpdatedAt
  },
  {
    id: "mc-nav-query",
    type: "navbar",
    title: "Sorgu Paneli",
    subtitle: "",
    description: "",
    body: "",
    category: "Navbar",
    tags: ["nav"],
    imageUrl: "",
    altText: "",
    icon: "",
    ctaLabel: "Sorgu Paneli",
    ctaHref: "/sorgu-paneli",
    status: "published",
    order: 3,
    isFeatured: false,
    createdAt: initialUpdatedAt,
    updatedAt: initialUpdatedAt
  },
  {
    id: "mc-nav-tools",
    type: "navbar",
    title: "Dijital Arac Merkezi",
    subtitle: "",
    description: "",
    body: "",
    category: "Navbar",
    tags: ["nav"],
    imageUrl: "",
    altText: "",
    icon: "",
    ctaLabel: "Dijital Arac Merkezi",
    ctaHref: "/dijital-arac-merkezi",
    status: "published",
    order: 4,
    isFeatured: false,
    createdAt: initialUpdatedAt,
    updatedAt: initialUpdatedAt
  },
  {
    id: "mc-stat-links",
    type: "stat",
    title: "Analiz edilen link",
    subtitle: "",
    description: "demo veri",
    body: "",
    category: "Sayaç",
    tags: ["demo"],
    imageUrl: "",
    altText: "",
    icon: "",
    ctaLabel: "",
    ctaHref: "",
    status: "published",
    order: 1,
    isFeatured: true,
    createdAt: initialUpdatedAt,
    updatedAt: initialUpdatedAt,
    dataMode: "demo",
    value: "12.480",
    detail: "demo veri"
  },
  {
    id: "mc-stat-risk",
    type: "stat",
    title: "Riskli sinyal yakalandi",
    subtitle: "",
    description: "site ve satici",
    body: "",
    category: "Sayaç",
    tags: ["demo"],
    imageUrl: "",
    altText: "",
    icon: "",
    ctaLabel: "",
    ctaHref: "",
    status: "published",
    order: 2,
    isFeatured: true,
    createdAt: initialUpdatedAt,
    updatedAt: initialUpdatedAt,
    dataMode: "demo",
    value: "1.936",
    detail: "site ve satici"
  },
  {
    id: "mc-stat-daily",
    type: "stat",
    title: "Gunluk analiz",
    subtitle: "",
    description: "ortalama demo",
    body: "",
    category: "Sayaç",
    tags: ["demo"],
    imageUrl: "",
    altText: "",
    icon: "",
    ctaLabel: "",
    ctaHref: "",
    status: "published",
    order: 3,
    isFeatured: true,
    createdAt: initialUpdatedAt,
    updatedAt: initialUpdatedAt,
    dataMode: "demo",
    value: "420",
    detail: "ortalama demo"
  },
  {
    id: "mc-announcement-home",
    type: "announcement",
    title: "Duyuru",
    subtitle: "Duyuru",
    description:
      "Demo bulten: Sahte kargo SMS'leri ve marka taklidi yapan linkler icin analiz panelini kullanarak risk sinyallerini kontrol edin.",
    body: "",
    category: "Duyuru",
    tags: ["demo", "uyari"],
    imageUrl: "",
    altText: "",
    icon: "!",
    ctaLabel: "",
    ctaHref: "",
    status: "published",
    order: 1,
    isFeatured: true,
    createdAt: initialUpdatedAt,
    updatedAt: initialUpdatedAt,
    dataMode: "demo",
    riskLevel: "info"
  },
  {
    id: "mc-cyber-news-kargo",
    type: "cyber-news",
    title: "Sahte kargo SMS'lerinde artis sinyali",
    subtitle: "Siber Gundem",
    description:
      "Kargo bekletme ve kucuk odeme talebi iceren mesajlarda linke tiklamadan once resmi uygulamadan kontrol yapilmasi onerilir.",
    body: "",
    category: "Siber Gundem",
    tags: ["sms", "phishing", "kargo"],
    imageUrl: "/logo.png",
    altText: "Sahte kargo SMS uyarisi",
    icon: "DI",
    ctaLabel: "Detayi Incele",
    ctaHref: "/sorgu-paneli?module=message",
    status: "published",
    order: 1,
    isFeatured: true,
    createdAt: initialUpdatedAt,
    updatedAt: initialUpdatedAt,
    dataMode: "demo",
    riskLevel: "risk",
    readTime: "3 dk",
    publishedAt: "2026-05-24",
    sourceLabel: "Dijital Iz Avcisi gozlem notu"
  },
  {
    id: "mc-cyber-news-edevlet",
    type: "cyber-news",
    title: "Resmi kurum alan adina benzeyen sayfalara dikkat",
    subtitle: "Phishing paterni",
    description:
      "Kurum adi iceren ancak resmi alan adiyla birebir eslesmeyen URL'ler kimlik bilgisi toplama amaciyla kullanilabilir.",
    body: "",
    category: "Siber Gundem",
    tags: ["domain", "phishing", "kurum"],
    imageUrl: "/logo.png",
    altText: "Resmi kurum alan adi uyarisi",
    icon: "DI",
    ctaLabel: "Detayi Incele",
    ctaHref: "/sorgu-paneli?module=phishing",
    status: "published",
    order: 2,
    isFeatured: false,
    createdAt: initialUpdatedAt,
    updatedAt: initialUpdatedAt,
    dataMode: "demo",
    riskLevel: "caution",
    readTime: "3 dk",
    publishedAt: "2026-05-24",
    sourceLabel: "Mock guvenlik bulteni"
  },
  {
    id: "mc-cyber-news-shopping",
    type: "cyber-news",
    title: "Alisveris oncesi satici ve yorum kontrolu",
    subtitle: "Alisveris Guvenligi",
    description:
      "Satici puani, yorum yogunlugu, iade sikayetleri ve fiyat anomalileri birlikte degerlendirildiginde daha saglikli karar verilebilir.",
    body: "",
    category: "Alisveris Guvenligi",
    tags: ["alisveris", "yorum", "satici"],
    imageUrl: "/logo.png",
    altText: "Alisveris guvenligi notu",
    icon: "DI",
    ctaLabel: "Detayi Incele",
    ctaHref: "/urun-analizi",
    status: "published",
    order: 3,
    isFeatured: false,
    createdAt: initialUpdatedAt,
    updatedAt: initialUpdatedAt,
    dataMode: "demo",
    riskLevel: "info",
    readTime: "3 dk",
    publishedAt: "2026-05-24",
    sourceLabel: "Platform onerisi"
  },
  {
    id: "mc-parser-trendyol",
    type: "parser-health",
    title: "Trendyol",
    subtitle: "aktif",
    description: "Temel urun adi, satici, fiyat ve puan alanlari okunabiliyor.",
    body: "",
    category: "Pazar yeri",
    tags: ["parser"],
    imageUrl: "",
    altText: "",
    icon: "",
    ctaLabel: "",
    ctaHref: "",
    status: "published",
    order: 1,
    isFeatured: true,
    createdAt: initialUpdatedAt,
    updatedAt: initialUpdatedAt,
    dataMode: "demo",
    value: "86",
    detail: "24.05.2026 22:40"
  },
  {
    id: "mc-parser-hepsiburada",
    type: "parser-health",
    title: "Hepsiburada",
    subtitle: "dikkat",
    description: "Dinamik iceriklerde Playwright fallback gerektirebilir.",
    body: "",
    category: "Pazar yeri",
    tags: ["parser"],
    imageUrl: "",
    altText: "",
    icon: "",
    ctaLabel: "",
    ctaHref: "",
    status: "published",
    order: 2,
    isFeatured: true,
    createdAt: initialUpdatedAt,
    updatedAt: initialUpdatedAt,
    dataMode: "demo",
    value: "68",
    detail: "24.05.2026 21:55"
  },
  {
    id: "mc-parser-n11",
    type: "parser-health",
    title: "N11",
    subtitle: "bakimda",
    description: "Selector sertlestirme ve ornek sayfa testi planlandi.",
    body: "",
    category: "Pazar yeri",
    tags: ["parser"],
    imageUrl: "",
    altText: "",
    icon: "",
    ctaLabel: "",
    ctaHref: "",
    status: "published",
    order: 3,
    isFeatured: true,
    createdAt: initialUpdatedAt,
    updatedAt: initialUpdatedAt,
    dataMode: "demo",
    value: "52",
    detail: "24.05.2026 20:30"
  },
  {
    id: "mc-step-link",
    type: "how-it-works",
    title: "Link yapistir",
    subtitle: "01",
    description: "Urun, site, IP veya mesaj bilgisini ilgili analiz paneline gir.",
    body: "",
    category: "Nasil calisir",
    tags: ["adim"],
    imageUrl: "",
    altText: "",
    icon: "01",
    ctaLabel: "",
    ctaHref: "",
    status: "published",
    order: 1,
    isFeatured: false,
    createdAt: initialUpdatedAt,
    updatedAt: initialUpdatedAt
  },
  {
    id: "mc-step-ai",
    type: "how-it-works",
    title: "AI analiz etsin",
    subtitle: "AI",
    description: "Parser, guvenlik kontrolleri ve AI ozetleme katmani risk paternlerini sade dile cevirir.",
    body: "",
    category: "Nasil calisir",
    tags: ["adim"],
    imageUrl: "",
    altText: "",
    icon: "AI",
    ctaLabel: "",
    ctaHref: "",
    status: "published",
    order: 2,
    isFeatured: false,
    createdAt: initialUpdatedAt,
    updatedAt: initialUpdatedAt
  },
  {
    id: "mc-step-result",
    type: "how-it-works",
    title: "Risk sonucunu ogren",
    subtitle: "OK",
    description: "Guven skoru, gorulen sinyaller ve kullanici onerileri tek raporda listelenir.",
    body: "",
    category: "Nasil calisir",
    tags: ["adim"],
    imageUrl: "",
    altText: "",
    icon: "OK",
    ctaLabel: "",
    ctaHref: "",
    status: "published",
    order: 3,
    isFeatured: false,
    createdAt: initialUpdatedAt,
    updatedAt: initialUpdatedAt
  },
  {
    id: "mc-guide-fake-site",
    type: "guide",
    title: "Sahte site nasil anlasilir?",
    subtitle: "Site guvenligi",
    description: "Alan adi, SSL, marka taklidi ve odeme sayfasi sinyallerini kontrol etmek icin pratik rehber.",
    body: "Resmi domaini, HTTPS durumunu, odeme sayfasi davranisini ve marka taklidi sinyallerini birlikte kontrol edin.",
    category: "Site guvenligi",
    tags: ["site", "phishing"],
    imageUrl: "",
    altText: "Sahte site rehberi",
    icon: "1",
    ctaLabel: "Rehberi Oku",
    ctaHref: "/siber-arsiv",
    status: "published",
    order: 1,
    isFeatured: true,
    createdAt: initialUpdatedAt,
    updatedAt: initialUpdatedAt,
    readTime: "4 dk",
    publishedAt: "2026-05-24"
  },
  {
    id: "mc-guide-sms",
    type: "guide",
    title: "Riskli SMS nasil tespit edilir?",
    subtitle: "Mesaj analizi",
    description: "Aciliyet baskisi, kurum taklidi, link yonlendirmesi ve kod talebi gibi paternleri ayirt edin.",
    body: "Mesajdaki korku dili, sure baskisi ve resmi olmayan linkler birlikte risk sinyali olusturabilir.",
    category: "Mesaj analizi",
    tags: ["sms", "phishing"],
    imageUrl: "",
    altText: "Riskli SMS rehberi",
    icon: "2",
    ctaLabel: "Rehberi Oku",
    ctaHref: "/sorgu-paneli?module=message",
    status: "published",
    order: 2,
    isFeatured: true,
    createdAt: initialUpdatedAt,
    updatedAt: initialUpdatedAt,
    readTime: "3 dk",
    publishedAt: "2026-05-24"
  },
  {
    id: "mc-guide-reviews",
    type: "guide",
    title: "Fake yorum nasil anlasilir?",
    subtitle: "Alisveris guvenligi",
    description: "Tekrarlayan ifade, ani puan artislari ve asiri benzer yorum sinyallerini sade sekilde okuyun.",
    body: "Yorum yogunlugu, tekrar eden kelimeler ve iade sikayetleri birlikte degerlendirilmelidir.",
    category: "Alisveris guvenligi",
    tags: ["yorum", "alisveris"],
    imageUrl: "",
    altText: "Fake yorum rehberi",
    icon: "3",
    ctaLabel: "Rehberi Oku",
    ctaHref: "/urun-analizi",
    status: "published",
    order: 3,
    isFeatured: true,
    createdAt: initialUpdatedAt,
    updatedAt: initialUpdatedAt,
    readTime: "5 dk",
    publishedAt: "2026-05-24"
  },
  {
    id: "mc-guide-instagram",
    type: "guide",
    title: "Instagram hesabi nasil korunur?",
    subtitle: "Siber farkindalik",
    description: "2FA, oturum kontrolu, fake destek mesajlari ve hesap kurtarma riskleri icin temel kontrol listesi.",
    body: "Cift asamali dogrulama, oturum kontrolleri ve fake destek mesajlarina karsi temkinli olmak temel savunmadir.",
    category: "Siber farkindalik",
    tags: ["instagram", "2fa"],
    imageUrl: "",
    altText: "Instagram hesap guvenligi rehberi",
    icon: "4",
    ctaLabel: "Rehberi Oku",
    ctaHref: "/siber-arsiv",
    status: "published",
    order: 4,
    isFeatured: true,
    createdAt: initialUpdatedAt,
    updatedAt: initialUpdatedAt,
    readTime: "4 dk",
    publishedAt: "2026-05-24"
  },
  {
    id: "mc-archive-wannacry",
    type: "cyber-archive",
    title: "WannaCry fidye yazilimi",
    subtitle: "Siber Kirilma Noktasi",
    description:
      "2017'de dunya genelinde bircok kurumu etkileyen fidye yazilimi olayi, yama yonetimi ve ag segmentasyonunun onemini gosterdi.",
    body:
      "Hastaneler, sirketler ve kamu kurumlari operasyonel kesinti yasadi; guncelleme yonetimi ve ag segmentasyonu guvenlik dersleri arasinda one cikti.",
    category: "Siber Arsiv",
    tags: ["ransomware", "wannacry", "tarih"],
    imageUrl: "",
    altText: "WannaCry siber olay karti",
    icon: "WC",
    ctaLabel: "Kaynak",
    ctaHref: "https://www.cisa.gov/news-events/alerts/2017/05/12/indicators-associated-wannacry-ransomware",
    status: "published",
    order: 1,
    isFeatured: true,
    createdAt: initialUpdatedAt,
    updatedAt: initialUpdatedAt,
    dataMode: "demo",
    riskLevel: "info",
    readTime: "4 dk",
    publishedAt: "2017-05-12",
    sourceLabel: "CISA"
  },
  {
    id: "mc-about-main",
    type: "about",
    title: "Siber farkindalik ve alisveris guvenligi icin sade risk analizi.",
    subtitle: "Hakkimizda",
    description:
      "Dijital Iz Avcisi, cevrim ici alisverislerde kullanicilarin urun ve satici risk sinyallerini daha hizli gorebilmesi icin gelistirilen AI destekli analiz platformudur.",
    body: "Sistem kesin hukum vermez. Sunulan sonuclar risk sinyalleri ve veri analizi temelinde olusturulan bilgilendirme ciktilaridir.",
    category: "Kurumsal",
    tags: ["hakkimizda"],
    imageUrl: "",
    altText: "",
    icon: "",
    ctaLabel: "",
    ctaHref: "",
    status: "published",
    order: 1,
    isFeatured: true,
    createdAt: initialUpdatedAt,
    updatedAt: initialUpdatedAt
  },
  {
    id: "mc-contact-intro",
    type: "contact",
    title: "Iletisim",
    subtitle: "Oneri ve Bildirim",
    description:
      "Supheli link, sahte SMS ornegi, hatali analiz bildirimi veya yeni ozellik onerilerini bu form uzerinden paylasabilirsiniz.",
    body: "",
    category: "Kurumsal",
    tags: ["iletisim"],
    imageUrl: "",
    altText: "",
    icon: "",
    ctaLabel: "Mesaj gonder",
    ctaHref: "/iletisim",
    status: "published",
    order: 1,
    isFeatured: true,
    createdAt: initialUpdatedAt,
    updatedAt: initialUpdatedAt
  },
  {
    id: "mc-legal-kvkk",
    type: "legal",
    title: "KVKK Bilgilendirme",
    subtitle: "Bilgilendirme",
    description:
      "Bu sayfa, Dijital Iz Avcisi platformunda islenen veriler hakkinda genel bilgilendirme amaciyla hazirlanmistir.",
    body:
      "Platform, analiz islemleri sirasinda kullanici tarafindan girilen link, mesaj metni veya benzeri icerikleri degerlendirebilir. Sunulan analizler kesin hukum degildir.",
    category: "kvkk",
    tags: ["yasal"],
    imageUrl: "",
    altText: "",
    icon: "",
    ctaLabel: "",
    ctaHref: "/kvkk",
    status: "published",
    order: 1,
    isFeatured: false,
    createdAt: initialUpdatedAt,
    updatedAt: initialUpdatedAt
  },
  {
    id: "mc-legal-privacy",
    type: "legal",
    title: "Gizlilik Politikasi",
    subtitle: "Bilgilendirme",
    description: "Dijital Iz Avcisi, kullanici guvenini merkeze alan sade ve seffaf bir veri yaklasimi hedefler.",
    body:
      "Platformun amaci geregi yalnizca analiz icin gerekli bilgiler islenir. Odeme bilgisi alinmaz ve gereksiz kisisel veri toplanmasi hedeflenmez.",
    category: "gizlilik",
    tags: ["yasal"],
    imageUrl: "",
    altText: "",
    icon: "",
    ctaLabel: "",
    ctaHref: "/gizlilik",
    status: "published",
    order: 2,
    isFeatured: false,
    createdAt: initialUpdatedAt,
    updatedAt: initialUpdatedAt
  },
  {
    id: "mc-legal-warning",
    type: "legal",
    title: "Yasal Uyari",
    subtitle: "Bilgilendirme",
    description: "Dijital Iz Avcisi, dijital risk sinyallerini anlasilir hale getiren bir farkindalik ve analiz platformudur.",
    body:
      "Platform ciktilari bir kisi, kurum, satici veya web sitesi hakkinda kesin suclama veya kesin guven beyani olusturmaz.",
    category: "yasal-uyari",
    tags: ["yasal"],
    imageUrl: "",
    altText: "",
    icon: "",
    ctaLabel: "",
    ctaHref: "/yasal-uyari",
    status: "published",
    order: 3,
    isFeatured: false,
    createdAt: initialUpdatedAt,
    updatedAt: initialUpdatedAt
  },
  {
    id: "mc-footer-main",
    type: "footer",
    title: "Dijital Iz Avcisi",
    subtitle: "Footer",
    description:
      "AI destekli analizler bilgilendirme amaclidir. Platform kesin suclama yapmaz; riskli davranis, phishing paterni ve supheli sinyal dilini kullanir.",
    body: "Platform bilgilendirme amaciyla risk sinyalleri uretir; kesin hukum veya suc isnadi olusturmaz.",
    category: "Footer",
    tags: ["footer"],
    imageUrl: "",
    altText: "",
    icon: "",
    ctaLabel: "",
    ctaHref: "",
    status: "published",
    order: 1,
    isFeatured: true,
    createdAt: initialUpdatedAt,
    updatedAt: initialUpdatedAt
  },
  {
    id: "mc-tool-phishing",
    type: "tool",
    title: "Sahte Link Analizi",
    subtitle: "Phishing kontrolu",
    description: "URL icin phishing paterni, marka taklidi, kisa link ve alan adi suphelerini degerlendirir.",
    body: "Phishing sinyali, typo domain, HTTPS, kisa link ve AI risk ozeti kontrolleri planlanir.",
    category: "Dijital Arac Merkezi",
    tags: ["phishing", "url"],
    imageUrl: "",
    altText: "Sahte link analizi araci",
    icon: "URL",
    ctaLabel: "Araci Ac",
    ctaHref: "/sorgu-paneli?module=phishing",
    status: "published",
    order: 1,
    isFeatured: true,
    createdAt: initialUpdatedAt,
    updatedAt: initialUpdatedAt
  },
  {
    id: "mc-useful-contact",
    type: "useful-link",
    title: "Supheli link bildir",
    subtitle: "Bildirim",
    description: "Karsilastiginiz supheli linkleri inceleme icin platforma iletin.",
    body: "",
    category: "Faydali link",
    tags: ["ihbar"],
    imageUrl: "",
    altText: "",
    icon: "!",
    ctaLabel: "Iletisime Git",
    ctaHref: "/iletisim",
    status: "published",
    order: 1,
    isFeatured: false,
    createdAt: initialUpdatedAt,
    updatedAt: initialUpdatedAt
  }
];
